version: '3.6'

services:
  nodejs_app:
    container_name: nodejs_app
    image: nodejs_app_image
    build: .
    ports:
      - '3000:3000'
      - '9229:9229'
    command:
      - yarn
      - 'run'
      - 'dev'
    volumes:
      - .:/usr/nodejs_app
